project:
  type: website
  output-dir: docs

website:
  title: "Environmental data from aquaculture sites" 
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Data overview"
        contents:
          - index.qmd
      - section: "Individual site details"
        contents:
          - Thorndyke_environmental_data.qmd
          - Hood_head_environmental_data.qmd
          - Eld_Inlet_environmental_data.qmd
          - ClamBay_environmental_data.qmd
          - Totten_data.qmd